### ISSUE TITLE
Python3 support not in PyPI

### ISSUE THREAD

**Issue by ulikoehler** [infrae/pyoai#24]
Commit https://github.com/infrae/pyoai/commit/beced901ea0b494f23053cbb3c6495872acb96a3 fixed a Python3 syntax issue in `client.py` but that commit is not included in the current release 2.4.5 on PyPI.

Here's the error message:
```
  File "[...]/pyoai-2.4.5-py3.5.egg/oaipmh/client.py", line 40
    raise Error, "Non-standard granularity on server: %s" % granularity
SyntaxError: invalid syntax
```
A preliminary workaround is to use
```
pip install git+https://github.com/infrae/pyoai.git
```
(depending on the configuration, you have to use `pip3` instead of `pip`)

Can you release a new version 2.4.6 in PyPI so this issue is resolved for Python3?

**Comment by mpasternak** [comment]
I e-mailed info@infrae.com about this.

**Comment by mpasternak** [comment]
@ulikoehler , I tried calling them. Their company phone no is dead too (after 2 beeps I get connection but all I can hear is static). 

Do we have any people in Rotterdam who could check out if infrae the company is alive?

**Comment by jascoul** [comment]
Hi guys, 
I'll have a look. I can make a release today.
Sorry about the miscommunication.

**Comment by mpasternak** [comment]
Hi @jascoul , from what I understand, you are a maintainer, right?

**Comment by jascoul** [comment]
Yes, I'm a maintainer.  I've been willing to do a release for ages, but didn't get round to doing it.
I'm still using  pyoai on python2.x, so the python3 support has been lacking.
If all the unittests run on py3, I will do a release. I'll also have a look at the client.py script.

**Comment by mpasternak** [comment]
Great to have you here! I just completed MOAI for Python 3k in my branch, I'll submit a pull request. The same thing is with pyoai, I also have it supporting Python 3k, I submitted a pull request to @ulikoehler 's branch, but there is no problem it can't be done with yours. 

There is also tox + travis support too. And badges. 

So, give me a day or two, I'll submit PRs for you. 

By the way, the first project to be converted to Py3 and released is pyoai, as MOAI depends on it. 

Check out my branches, let's not double the efforts. Thanks!

**Comment by mpasternak** [comment]
Look at this beauty: https://github.com/mpasternak/pyoai https://travis-ci.org/mpasternak/pyoai

**Comment by mpasternak** [comment]
... and this one: https://github.com/mpasternak/moai https://travis-ci.org/mpasternak/moai

**Comment by jascoul** [comment]
That's great! 
Can you make a pull request for your latest version? Maybe I can just merge that and put it on pypi?

**Comment by mpasternak** [comment]
@jascoul Pull requests created for both pyoai and moai. Please review. Please remember you need to release pyoai first if moai has to depend on the wheel version (currently it depends on the version from GitHub in tox.ini)

**Comment by jascoul** [comment]
I merged the changes and created a new release (pyoai 2.5.0) which is now on pypi. I will contact Infrae and see if we can transfer the repository. Thanks guys.
