### ISSUE TITLE
from_ and until arguments throw error 

### ISSUE THREAD

**Issue by ebauch** [infrae/pyoai#29]
I am trying to restrict the number of papers to download from Pubmed using the from_ and until arguments, however, that doesn't work, no matter what I try. Without from/until arguments the code just works fine. The error is 

![image](https://user-images.githubusercontent.com/3758223/30811997-bc28fe96-a1d7-11e7-9a91-e57288a31d01.png)

I tried arxiv.org, but no success either. Here is a minimal example: 

```
import datetime
from oaipmh.client import Client
from oaipmh.metadata import MetadataRegistry, oai_dc_reader

# specify from date
from_date ='2017-01-01'
from_date = datetime.datetime.strptime(from_date, "%Y-%m-%d")

# pubmed url
url = "https://www.ncbi.nlm.nih.gov/pmc/oai/oai.cgi"

registry = MetadataRegistry()
registry.registerReader('oai_dc', oai_dc_reader)
client = Client(url, registry)
serverinfo = client.identify()
print(serverinfo.repositoryName())

ids = []
for record in client.listIdentifiers(metadataPrefix='oai_dc', from_=from_date):
     
    ids.append(record.identifier())
    
print('total # of ids:', len(ids))

```

Note also this  #7 : I believe the from_ and until arguments need to be specified as datetimes, not strings. 

The error indicates that the datetime format is wrongly formated. It appears that pubmed DOES NOT support the time argument. For example, this request work just fine without time specified: 

https://www.ncbi.nlm.nih.gov/pmc/oai/oai.cgi?verb=ListIdentifiers&from=2002-01-01&metadataPrefix=oai_dc

With time specified it fails with the same error as stated above: 

https://www.ncbi.nlm.nih.gov/pmc/oai/oai.cgi?verb=ListIdentifiers&from=2002-01-01T00:00:00Z&metadataPrefix=pmc_fm

**Comment by jascoul** [comment]
What is happening here is that pyoai sends the from argument to the Pubmed server in full datetime granularity (YYYY-MM-DDTHH:MM:SSZ) but the Pubmed server only understands day granularity (YYYY-MM-DD). The error message is coming from the Pubmed server (like you already found out with your last link).

You can force the client to take this into account using the updateGranularity method:

```
client = Client(url, registry)                                                                                         
client.updateGranularity() 
for record in client.listIdentifiers(metadataPrefix='oai_dc', from_=from_date):
    ...
```

I'm not sure why this does not happen by default. Maybe we can change this in a future release.
