### ISSUE TITLE
Create o modify the fields of metadata

### ISSUE THREAD

**Issue by LeonardoLed** [infrae/pyoai#34]
Hi there, I have already installed this package:

https://github.com/infrae/moai

In order to have a little Open Access Server Platform but this installation have a standard fields, I want to change for another types of fields that it shows below:

![image](https://user-images.githubusercontent.com/33387734/51098199-a99dd980-178e-11e9-98ba-401b42c884ce.png)
![image](https://user-images.githubusercontent.com/33387734/51098217-bd494000-178e-11e9-9991-d0c858cc6e07.png)

Is there easy way to do this? 
Thanks

Regards

**Comment by interrogator** [comment]
I don't think this issue is fully specified, have no idea what help for it wold look like. Any chance of clarification of what you're trying to do, @LeonardoLed ? Are you still having an issue? Can you describe it in more detail?
