### ISSUE TITLE
Description in setup.py should be a single line

### ISSUE THREAD

**Issue by tahme** [infrae/pyoai#50]
Newlines in setup.py description are disallowed and some versions of setuptools (e.g. v59.0.1) fail to install pyoai, giving a `ValueError: Newlines are not allowed`.

See https://github.com/pypa/setuptools/pull/2870 (reverted in https://github.com/pypa/setuptools/commit/68795af92cff7929d56d6b8753a8621ad12444fb but is expected to break again later).

**Comment by wetneb** [comment]
Thanks for the report, I fixed this.
